name: Ubuntu 22.04 CI (GCC 11) with Sanitizers

on: [push, pull_request]

jobs:
  ubuntu-build:
    if: >-
      ! contains(toJSON(github.event.commits.*.message), '[skip ci]') &&
      ! contains(toJSON(github.event.commits.*.message), '[skip github]')
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Use cmake
        run: |
          mkdir builddebug &&
          cd builddebug &&
          cmake -DIS_UTF8_SANITIZE=ON -DCMAKE_BUILD_TYPE=Debug ..  &&
          cmake --build .   &&
          ctest -j --output-on-failure -LE explicitonly   &&
          cd .. &&
          mkdir build &&
          cd build &&
          cmake -DIS_UTF8_SANITIZE=ON ..  &&
          cmake --build .   &&
          ctest -j --output-on-failure -LE explicitonly
